# This file was generated by GoReleaser. DO NOT EDIT.
cask "golden-rules" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "a7e94959d7c44e7c86958c0ed06e5b38ad48b9cdc69ec0246480cde838b65c20"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dbdbeb4de7077b035a7436734da46c6c4eaa1c24d0a653f27c96c2c7a1d597e2"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ced808c6f05394e793d8c6c807cfd6ec00811a56302c4bee308a916a23903290"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49aa745c10084ea2db5c3ba6b2113fbb27ba77fb012acf462690478850d66267"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_linux_amd64.tar.gz"
    end
  end

  name "golden-rules"
  desc "Install the /golden-rules skill and its plugins for Claude Code"
  homepage "https://github.com/idrispwala-web/golden-rules"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golden-rules"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golden-rules"]
    end
  end

  # No zap stanza required
end
