# This file was generated by GoReleaser. DO NOT EDIT.
cask "golden-rules" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "38dcb961b4b2024cef97c3238c05bc22e91388bafd3a9aac908954efcf2a1906"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "570917f8c2fed3cdebe81d7145448dc12a344d37277e788bfc02a68b688578c1"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f7e5ad26bcbc53ae81b27f165982d55c3884975f4a26ef454989f85538f0b1de"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "47f11d5a4742c5ec0d917ba03352ecfe700efa2e29ed7ef4cb78aaf5fdca6dce"
      url "https://github.com/idrispwala-web/golden-rules/releases/download/v#{version}/golden-rules_#{version}_linux_amd64.tar.gz"
    end
  end

  name "golden-rules"
  desc "Install the /golden-rules skill and its plugins for Claude Code"
  homepage "https://github.com/idrispwala-web/golden-rules"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golden-rules"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golden-rules"]
    end
  end

  # No zap stanza required
end
